about OneCalendar in documentation
Kozea/Radicale pull request #1073
Opened 2020-06-30 07:07 UTC by peetervois

I found a client for Android that works very well. Tested with 2.1 of Radicale.

2023-12-28 19:20 UTC, bosd approved these changes

2024-03-01 05:04 UTC, pbiering requested changes
Please rebase to lastest Radicale 3 after confirmation that "OneCalendar" is also working with that version.

2024-12-31 21:20 UTC, Neustradamus commented
@peetervois: Can you rebase your PR?

2025-01-03 06:20 UTC, pbiering commented
fixed by different commit

2025-01-03 06:20 UTC, closed without merging