Listen on IPv4 and IPv6
Kozea/Radicale pull request #1260
Opened 2022-09-22 02:16 UTC by porjo

Dockerfile currently only listens on IPv4. This change makes it listen on IPv6 also.

Fixes #1138

2024-03-01 05:25 UTC, pbiering requested changes
Please rebase to lastest Radicale 3

2024-03-01 10:08 UTC, porjo reviewed
Using latest v3 now

2024-03-01 20:15 UTC, pbiering commented
> Using latest v3 now

Thank you, while not having "Docker" here, is this still working in case IPv6 is not available on a particular setup?

2024-03-01 23:18 UTC, porjo commented
> Thank you, while not having "Docker" here, is this still working in case IPv6 is not available on a particular setup?

It's a good question. I tested like this: 
```
docker run -it --rm --entrypoint /bin/ash --sysctl net.ipv6.conf.all.disable_ipv6=1 radicale
/app $ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: tap0: <BROADCAST,UP,LOWER_UP> mtu 65520 qdisc fq_codel state UNKNOWN qlen 1000
    link/ether b2:c9:0a:15:c2:ac brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.100/24 brd 10.0.2.255 scope global tap0
       valid_lft forever preferred_lft forever
/app $ bin/python bin/radicale --hosts [::]:5232 &
/app $ netstat -an
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 :::5232                 :::*                    LISTEN   
```
So the container indicates no IPv6 and Radicale starts without error when given the `[::]:5232` hosts value.

2024-03-02 04:38 UTC, pbiering approved these changes

2024-03-02 04:40 UTC, merged